### ISSUE TITLE
Consistency in using " " or ' '

### ISSUE THREAD

**Issue by HilbertSpitzer** [FACN4/BSN_week1-group-project#13]
For example at: **div class=**
https://github.com/FACN4/BSN_week1-group-project/blob/master/index.html#L20
https://github.com/FACN4/BSN_week1-group-project/blob/master/index.html#L42

Or at: **type=**
https://github.com/FACN4/BSN_week1-group-project/blob/master/index.html#L68-72
https://github.com/FACN4/BSN_week1-group-project/blob/master/index.html#L73

**Comment by noorafi** [comment]
worked on it issue solved :
