### ISSUE TITLE
Team description not appearing well on mobile

### ISSUE THREAD

**Issue by MynahMarie** [FACN4/BSN_week1-group-project#15]
When viewing your site on mobile, to increase readability, the descriptions of each team member should appear stacked (one on top of the other) instead of one besides each other as shown in the screenshot. 

![screenshot 2018-07-05 10 43 07](https://user-images.githubusercontent.com/24983802/42309065-3e0abf3e-8040-11e8-84f3-db161ef916ce.jpg)

**Comment by BenNewman90** [comment]
resolved. Had to add `  <meta name="viewport" content="width=device-width, initial-scale=1">`
