### ISSUE TITLE
Add to Readme.md

### ISSUE THREAD

**Issue by haydnba** [FACN4/BSN_week1-group-project#16]
You've made an excellent start on the readme for this project but when you get a chance it would be useful for visitors to the repository if you add further details. For example:
* list the user stories (requirements) and specify how you respond to each
* add a link at the top of the readme to your live site ([find our site at](facn4.github.io/BSN_week1-group-project/))
* a little more detail on why you specify certain constraints in the section on form validation

🤓

**Comment by MynahMarie** [comment]
I would like to add to this that the `How` section can be a bit more descriptive, for example you are not mentioning that you are using `formspree.io` anywhere in the README. This information can be interesting and is worth mentioning and elaborating upon. As well, it would be nice to expand more on how exactly you implemented validation for your contact form (so not just listing the constraints but how are these constraints implemented).
