### ISSUE TITLE
Using classes in CSS instead of native html tags

### ISSUE THREAD

**Issue by MynahMarie** [FACN4/BSN_week1-group-project#18]
For small projects like this one, defining a style directly for the native html tags (like `<p>`, `<ul>`, `<nav>`, ...) can be fine because you will only have a limited number of instances of those tags. But as the projects grow larger this method will become very difficult to maintain. It's better to develop the good habit from the start to define css classes and then apply those classes in the html. This will allow a much more precise customization of html elements.

https://github.com/FACN4/BSN_week1-group-project/blob/c172a719a4c08412cc99693de93d2d4e8da87d2a/style.css#L21-L42

**Comment by BenNewman90** [comment]
Good point. resolved.
