### ISSUE TITLE
Form-Autofill

### ISSUE THREAD

**Issue by Ryan2601** [FACN4/BSN_week1-group-project#23]
Form doesn't work with google autofill even though the fields are filled with valid information.

![screenshot from 2018-07-05 11-08-00](https://user-images.githubusercontent.com/39595382/42310374-f004c34e-8043-11e8-8305-2b3ded32ebdd.png)

**Comment by BenNewman90** [comment]
Not an issue

**Comment by BenNewman90** [comment]
Not an issue with my browser.
