### ISSUE TITLE
Unreadable text 

### ISSUE THREAD

**Issue by tawfiknasser** [FACN4/BSN_week1-group-project#33]
![ca4f4f80-1e7d-438b-a602-76e94c1f8353](https://user-images.githubusercontent.com/36166288/42311170-dfd1353c-8045-11e8-9981-30ecdf2d17aa.jpeg)

unreadable text under the images on mobile version

you might make it appear in one column

**Comment by BenNewman90** [comment]
Resolved. Had to add `  <meta name="viewport" content="width=device-width, initial-scale=1">` to the top of the page.
